name: brain_tumor_torch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tensorflow=2.10
  - keras
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - opencv
  - nibabel
  - tqdm 